// ============================================================
// LAYE MOVIES — Legal Movie Database
// All movies are public domain, Creative Commons, or officially
// distributed for free by rights holders.
// ============================================================

const MOVIES = [
  // ── CLASSIC CINEMA ──────────────────────────────────────
  {
    id: "nosferatu-1922",
    title: "Nosferatu",
    year: 1922,
    director: "F.W. Murnau",
    cast: ["Max Schreck", "Gustav von Wangenheim", "Greta Schröder"],
    genre: ["Horror", "Classic Cinema"],
    language: "de",
    country: "Germany",
    runtime: 94,
    rating: 7.9,
    description: "A vampire Count moves from Transylvania to Germany, bringing with him a plague and terrorizing an innocent couple. One of the greatest horror films ever made and a landmark of German Expressionism.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Nosferatu_Hutter_Knock.jpg/800px-Nosferatu_Hutter_Knock.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Nosferatu%2C_eine_Symphonie_des_Grauens_%281922%29.jpg/1200px-Nosferatu%2C_eine_Symphonie_des_Grauens_%281922%29.jpg",
    watchUrl: "https://archive.org/details/Nosferatu_201310",
    embedUrl: "https://archive.org/embed/Nosferatu_201310",
    trailerUrl: null,
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["expressionism", "vampire", "silent", "german", "horror", "iconic"],
    featured: true,
    trending: true
  },
  {
    id: "metropolis-1927",
    title: "Metropolis",
    year: 1927,
    director: "Fritz Lang",
    cast: ["Brigitte Helm", "Gustav Fröhlich", "Alfred Abel"],
    genre: ["Science Fiction", "Classic Cinema"],
    language: "de",
    country: "Germany",
    runtime: 153,
    rating: 8.3,
    description: "In a futuristic city sharply divided between the working class and the city planners, the son of the city's mastermind falls in love with a working-class prophet. A monumental science-fiction epic.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Metropolis_Film_Plakat.jpg/800px-Metropolis_Film_Plakat.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/1/18/Metropolis_%281927_film%29.jpg",
    watchUrl: "https://archive.org/details/Metropolis_1927",
    embedUrl: "https://archive.org/embed/Metropolis_1927",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["dystopia", "silent", "sci-fi", "futurism", "masterpiece"],
    featured: true,
    trending: true
  },
  {
    id: "cabinet-dr-caligari-1920",
    title: "The Cabinet of Dr. Caligari",
    year: 1920,
    director: "Robert Wiene",
    cast: ["Werner Krauss", "Conrad Veidt", "Friedrich Fehér"],
    genre: ["Horror", "Classic Cinema"],
    language: "de",
    country: "Germany",
    runtime: 76,
    rating: 8.0,
    description: "A mysterious doctor and his somnambulist commit a series of murders. A groundbreaking expressionist horror film with unforgettable angular sets and disturbing visuals.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Das_Cabinet_des_Dr._Caligari_poster.jpg/800px-Das_Cabinet_des_Dr._Caligari_poster.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Caligari_01.jpg",
    watchUrl: "https://archive.org/details/TheCabinetOfDr.Caligari",
    embedUrl: "https://archive.org/embed/TheCabinetOfDr.Caligari",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["expressionism", "silent", "horror", "german", "surreal"],
    featured: false,
    trending: false
  },
  {
    id: "general-1926",
    title: "The General",
    year: 1926,
    director: "Buster Keaton",
    cast: ["Buster Keaton", "Marion Mack", "Glen Cavender"],
    genre: ["Comedy", "Classic Cinema", "Adventure"],
    language: "en",
    country: "USA",
    runtime: 79,
    rating: 8.1,
    description: "During the Civil War, a Confederate train engineer tries to recover his beloved locomotive and his girlfriend. Buster Keaton's masterpiece and one of the greatest comedies ever made.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Poster_of_the_movie_The_General.jpg/800px-Poster_of_the_movie_The_General.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Buster_Keaton_in_The_General_still.jpg",
    watchUrl: "https://archive.org/details/TheGeneral_201407",
    embedUrl: "https://archive.org/embed/TheGeneral_201407",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["silent", "comedy", "keaton", "civil war", "slapstick"],
    featured: true,
    trending: false
  },
  {
    id: "city-lights-1931",
    title: "City Lights",
    year: 1931,
    director: "Charlie Chaplin",
    cast: ["Charlie Chaplin", "Virginia Cherrill", "Florence Lee"],
    genre: ["Comedy", "Drama", "Classic Cinema"],
    language: "en",
    country: "USA",
    runtime: 87,
    rating: 8.5,
    description: "The Tramp falls in love with a blind flower girl and tries to raise money for an operation that will restore her sight. Chaplin's most beloved film and a true cinematic masterpiece.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/City_Lights_poster.jpg/800px-City_Lights_poster.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/8/87/City_Lights_Chaplin.jpg",
    watchUrl: "https://archive.org/details/city-lights-charlie-chaplin",
    embedUrl: "https://archive.org/embed/city-lights-charlie-chaplin",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["chaplin", "tramp", "silent", "comedy", "romance", "iconic"],
    featured: true,
    trending: true
  },
  {
    id: "night-hunter-1924",
    title: "Sherlock Jr.",
    year: 1924,
    director: "Buster Keaton",
    cast: ["Buster Keaton", "Kathryn McGuire", "Joe Keaton"],
    genre: ["Comedy", "Classic Cinema"],
    language: "en",
    country: "USA",
    runtime: 45,
    rating: 8.2,
    description: "A film projectionist dreams himself into a mystery movie to solve a crime. Keaton's most technically inventive film, with stunning practical effects that still amaze a century later.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Sherlock_Jr_1924_Film_Poster.jpg/800px-Sherlock_Jr_1924_Film_Poster.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/c/c9/Sherlock_Jr_1924_Buster_Keaton.jpg",
    watchUrl: "https://archive.org/details/SherlocJr1924",
    embedUrl: "https://archive.org/embed/SherlocJr1924",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["silent", "comedy", "keaton", "meta", "inventive"],
    featured: false,
    trending: true
  },
  // ── PUBLIC DOMAIN ──────────────────────────────────────
  {
    id: "night-living-dead-1968",
    title: "Night of the Living Dead",
    year: 1968,
    director: "George A. Romero",
    cast: ["Duane Jones", "Judith O'Dea", "Karl Hardman"],
    genre: ["Horror", "Classic Cinema"],
    language: "en",
    country: "USA",
    runtime: 96,
    rating: 7.9,
    description: "A group of people hide from bloodthirsty zombies in a farmhouse. Romero's genre-defining horror film that invented the modern zombie and remains a powerful social commentary.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Night_of_the_living_dead_affiche.jpg/800px-Night_of_the_living_dead_affiche.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Night_of_the_Living_Dead_%281968%29_original_poster.jpg",
    watchUrl: "https://archive.org/details/night_of_the_living_dead",
    embedUrl: "https://archive.org/embed/night_of_the_living_dead",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["zombie", "horror", "romero", "social commentary", "b-movie"],
    featured: true,
    trending: true
  },
  {
    id: "his-girl-friday-1940",
    title: "His Girl Friday",
    year: 1940,
    director: "Howard Hawks",
    cast: ["Cary Grant", "Rosalind Russell", "Ralph Bellamy"],
    genre: ["Comedy", "Drama", "Classic Cinema"],
    language: "en",
    country: "USA",
    runtime: 92,
    rating: 7.9,
    description: "A newspaper editor uses and manipulates his star reporter ex-wife to cover a story. A screwball comedy classic with some of the fastest dialogue ever put to film.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/His_Girl_Friday.jpg/800px-His_Girl_Friday.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/0/0b/His_Girl_Friday.jpg",
    watchUrl: "https://archive.org/details/HisGirlFriday1940",
    embedUrl: "https://archive.org/embed/HisGirlFriday1940",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["screwball", "comedy", "cary grant", "journalism", "fast-talking"],
    featured: false,
    trending: false
  },
  {
    id: "little-shop-horrors-1960",
    title: "The Little Shop of Horrors",
    year: 1960,
    director: "Roger Corman",
    cast: ["Jonathan Haze", "Jackie Joseph", "Mel Welles"],
    genre: ["Comedy", "Horror"],
    language: "en",
    country: "USA",
    runtime: 72,
    rating: 6.6,
    description: "A clumsy young man nurtures a plant which turns out to have a taste for human flesh. Shot in two days, this cult classic inspired a beloved musical and represents the best of B-movie charm.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/The-little-shop-of-horrors.jpg/800px-The-little-shop-of-horrors.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/e/ea/The-little-shop-of-horrors.jpg",
    watchUrl: "https://archive.org/details/TheLittleShopOfHorrors_201510",
    embedUrl: "https://archive.org/embed/TheLittleShopOfHorrors_201510",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["cult", "b-movie", "corman", "plants", "horror-comedy"],
    featured: false,
    trending: false
  },
  {
    id: "carnival-souls-1962",
    title: "Carnival of Souls",
    year: 1962,
    director: "Herk Harvey",
    cast: ["Candace Hilligoss", "Frances Feist", "Sidney Berger"],
    genre: ["Horror"],
    language: "en",
    country: "USA",
    runtime: 78,
    rating: 7.1,
    description: "After a car accident, a woman is haunted by a mysterious phantom figure. Made for only $33,000, this eerie horror film influenced countless filmmakers including David Lynch and George Romero.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Carnival_of_Souls.jpg/800px-Carnival_of_Souls.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/7/70/Carnival_of_Souls.jpg",
    watchUrl: "https://archive.org/details/CarnivalOfSouls",
    embedUrl: "https://archive.org/embed/CarnivalOfSouls",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["cult", "eerie", "atmospheric", "low-budget", "art-house"],
    featured: false,
    trending: true
  },
  // ── DOCUMENTARIES ───────────────────────────────────────
  {
    id: "nanook-north-1922",
    title: "Nanook of the North",
    year: 1922,
    director: "Robert J. Flaherty",
    cast: ["Allakariallak", "Nyla", "Allee"],
    genre: ["Documentary"],
    language: "en",
    country: "USA",
    runtime: 79,
    rating: 7.5,
    description: "A documentary following the life of Nanook and his family in the Canadian Arctic. Considered the first feature-length documentary film and a landmark of cinema history.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Nanook_of_the_North_%281922%29.jpg/800px-Nanook_of_the_North_%281922%29.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Nanook_of_the_North_%281922%29.jpg",
    watchUrl: "https://archive.org/details/nanook-of-the-north-1922",
    embedUrl: "https://archive.org/embed/nanook-of-the-north-1922",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["documentary", "arctic", "ethnographic", "first", "silent"],
    featured: false,
    trending: false
  },
  {
    id: "triumph-will-1935",
    title: "Man with a Movie Camera",
    year: 1929,
    director: "Dziga Vertov",
    cast: [],
    genre: ["Documentary", "Classic Cinema"],
    language: "ru",
    country: "USSR",
    runtime: 68,
    rating: 8.3,
    description: "An experimental documentary without narrative, actors, or intertitles that captures daily life in Soviet cities through innovative cinematic techniques. A revolutionary work of avant-garde filmmaking.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Man_with_a_movie_camera.jpg/800px-Man_with_a_movie_camera.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/2/22/Man_with_a_movie_camera.jpg",
    watchUrl: "https://archive.org/details/Man_with_a_Movie_Camera",
    embedUrl: "https://archive.org/embed/Man_with_a_Movie_Camera",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["avant-garde", "experimental", "soviet", "silent", "documentary"],
    featured: true,
    trending: false
  },
  // ── SCIENCE FICTION ─────────────────────────────────────
  {
    id: "trip-moon-1902",
    title: "A Trip to the Moon",
    year: 1902,
    director: "Georges Méliès",
    cast: ["Georges Méliès", "Victor André", "Bleuette Bernon"],
    genre: ["Science Fiction", "Classic Cinema", "Adventure"],
    language: "fr",
    country: "France",
    runtime: 13,
    rating: 8.2,
    description: "A group of astronomers travel to the Moon in a cannon-propelled capsule. The first science fiction film ever made, featuring Méliès' iconic special effects and the unforgettable image of a rocket in the Moon's eye.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Le_Voyage_dans_la_lune.jpg/800px-Le_Voyage_dans_la_lune.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Le_Voyage_dans_la_lune.jpg",
    watchUrl: "https://archive.org/details/LeVoyageDansLaLune",
    embedUrl: "https://archive.org/embed/LeVoyageDansLaLune",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["méliès", "first sci-fi", "silent", "moon", "french", "short"],
    featured: true,
    trending: true
  },
  {
    id: "invisible-man-1933",
    title: "The Invisible Man",
    year: 1933,
    director: "James Whale",
    cast: ["Claude Rains", "Gloria Stuart", "William Harrigan"],
    genre: ["Science Fiction", "Horror", "Classic Cinema"],
    language: "en",
    country: "USA",
    runtime: 71,
    rating: 7.7,
    description: "A scientist discovers a formula for invisibility. Based on H.G. Wells' novel, this thriller features groundbreaking special effects and a chilling performance by Claude Rains.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/InvisibleManPoster.jpg/800px-InvisibleManPoster.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/6/6b/InvisibleManPoster.jpg",
    watchUrl: "https://archive.org/details/the-invisible-man-1933",
    embedUrl: "https://archive.org/embed/the-invisible-man-1933",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["h.g. wells", "invisibility", "horror", "sci-fi", "universal monsters"],
    featured: false,
    trending: false
  },
  // ── ANIMATION ───────────────────────────────────────────
  {
    id: "steamboat-willie-1928",
    title: "Steamboat Willie",
    year: 1928,
    director: "Walt Disney",
    cast: [],
    genre: ["Animation", "Comedy"],
    language: "en",
    country: "USA",
    runtime: 8,
    rating: 7.3,
    description: "Mickey Mouse pilots a steamboat while whistling. The first Disney cartoon with synchronized sound and the debut of Mickey Mouse, now entered the public domain in 2024.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Steamboat-willie.jpg/800px-Steamboat-willie.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/8/85/Steamboat-willie.jpg",
    watchUrl: "https://archive.org/details/steamboat-willie",
    embedUrl: "https://archive.org/embed/steamboat-willie",
    license: "Public Domain (2024)",
    source: "Internet Archive",
    tags: ["mickey mouse", "disney", "animation", "first sound cartoon", "short"],
    featured: true,
    trending: true
  },
  {
    id: "popeye-1933",
    title: "Popeye the Sailor",
    year: 1933,
    director: "Dave Fleischer",
    cast: [],
    genre: ["Animation", "Comedy"],
    language: "en",
    country: "USA",
    runtime: 7,
    rating: 7.0,
    description: "Popeye the Sailor and Bluto compete for the affections of Olive Oyl. Classic Fleischer Studios animation at its finest, featuring the debut of the beloved spinach-powered sailor.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Popeye_the_Sailor.png/800px-Popeye_the_Sailor.png",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Popeye_the_Sailor.png",
    watchUrl: "https://archive.org/details/popeye-the-sailor-1933",
    embedUrl: "https://archive.org/embed/popeye-the-sailor-1933",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["popeye", "fleischer", "animation", "short", "classic cartoon"],
    featured: false,
    trending: false
  },
  // ── DRAMA ────────────────────────────────────────────────
  {
    id: "battleship-potemkin-1925",
    title: "Battleship Potemkin",
    year: 1925,
    director: "Sergei Eisenstein",
    cast: ["Aleksandr Antonov", "Vladimir Barsky", "Grigori Aleksandrov"],
    genre: ["Drama", "Historical Films", "Classic Cinema"],
    language: "ru",
    country: "USSR",
    runtime: 75,
    rating: 8.0,
    description: "A dramatization of a 1905 mutiny on the battleship Potemkin. Eisenstein's revolutionary film is famous for its Odessa Steps sequence and remains one of the most influential films in history.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Bronenosets_Potyomkin_1925.jpg/800px-Bronenosets_Potyomkin_1925.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/4/47/Bronenosets_Potyomkin_1925.jpg",
    watchUrl: "https://archive.org/details/BattleshipPotemkin",
    embedUrl: "https://archive.org/embed/BattleshipPotemkin",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["soviet", "silent", "montage", "revolutionary", "political"],
    featured: true,
    trending: false
  },
  {
    id: "grapes-wrath-1940",
    title: "Mr. Smith Goes to Washington",
    year: 1939,
    director: "Frank Capra",
    cast: ["James Stewart", "Jean Arthur", "Claude Rains"],
    genre: ["Drama", "Classic Cinema"],
    language: "en",
    country: "USA",
    runtime: 129,
    rating: 8.1,
    description: "A naive idealist is appointed to fill a vacancy in the US Senate, where he fights against a corrupt political machine. Capra's masterwork of American idealism and democracy.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Mr._Smith_Goes_to_Washington.jpg/800px-Mr._Smith_Goes_to_Washington.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Mr._Smith_Goes_to_Washington.jpg",
    watchUrl: "https://archive.org/details/mr-smith-goes-to-washington-1939",
    embedUrl: "https://archive.org/embed/mr-smith-goes-to-washington-1939",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["capra", "politics", "idealism", "james stewart", "american"],
    featured: false,
    trending: true
  },
  // ── INDEPENDENT FILMS ────────────────────────────────────
  {
    id: "reefer-madness-1936",
    title: "Reefer Madness",
    year: 1936,
    director: "Louis J. Gasnier",
    cast: ["Dorothy Short", "Kenneth Craig", "Lillian Miles"],
    genre: ["Drama", "Independent Movies"],
    language: "en",
    country: "USA",
    runtime: 68,
    rating: 3.6,
    description: "High school students are lured by pushers to try marijuana, with disastrous consequences. An unintentionally hilarious propaganda film that became a cult classic for all the wrong reasons.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Reefer_Madness_poster.jpg/800px-Reefer_Madness_poster.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Reefer_Madness_poster.jpg",
    watchUrl: "https://archive.org/details/ReeferMadness",
    embedUrl: "https://archive.org/embed/ReeferMadness",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["cult", "propaganda", "camp", "b-movie", "unintentional comedy"],
    featured: false,
    trending: false
  },
  {
    id: "buck-rogers-1939",
    title: "Buck Rogers",
    year: 1939,
    director: "Ford Beebe",
    cast: ["Buster Crabbe", "Constance Moore", "Jackie Moran"],
    genre: ["Science Fiction", "Adventure"],
    language: "en",
    country: "USA",
    runtime: 239,
    rating: 6.5,
    description: "Buck Rogers and his companion are frozen in a dirigible and awaken 500 years in the future, where they fight against the villain Killer Kane. The classic serial adventure that inspired generations of sci-fi.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Buck_rogers_1939.jpg/800px-Buck_rogers_1939.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Buck_rogers_1939.jpg",
    watchUrl: "https://archive.org/details/buck_rogers_serial_1939",
    embedUrl: "https://archive.org/embed/buck_rogers_serial_1939",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["serial", "sci-fi", "adventure", "space", "pulp"],
    featured: false,
    trending: false
  },
  // ── ADVENTURE ────────────────────────────────────────────
  {
    id: "robin-hood-1922",
    title: "Robin Hood",
    year: 1922,
    director: "Allan Dwan",
    cast: ["Douglas Fairbanks", "Wallace Beery", "Sam De Grasse"],
    genre: ["Adventure", "Classic Cinema"],
    language: "en",
    country: "USA",
    runtime: 143,
    rating: 7.2,
    description: "The Earl of Huntingdon becomes the outlaw Robin Hood to fight for justice against the tyranny of the Sheriff of Nottingham and Prince John. A spectacular silent epic with incredible production design.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Robin_Hood_1922_film_poster.jpg/800px-Robin_Hood_1922_film_poster.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/d/dc/Robin_Hood_1922_film_poster.jpg",
    watchUrl: "https://archive.org/details/RobinHood1922",
    embedUrl: "https://archive.org/embed/RobinHood1922",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["robin hood", "silent", "swashbuckler", "fairbanks", "medieval"],
    featured: false,
    trending: false
  },
  {
    id: "thief-bagdad-1924",
    title: "The Thief of Bagdad",
    year: 1924,
    director: "Raoul Walsh",
    cast: ["Douglas Fairbanks", "Julanne Johnston", "Anna May Wong"],
    genre: ["Adventure", "Fantasy", "Classic Cinema"],
    language: "en",
    country: "USA",
    runtime: 155,
    rating: 7.7,
    description: "A thief uses a magic chest and other treasures to win the hand of a princess. An extravagant Arabian Nights fantasy with stunning sets and Douglas Fairbanks at the peak of his acrobatic powers.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Thief_of_Bagdad_%281924%29.jpg/800px-Thief_of_Bagdad_%281924%29.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Thief_of_Bagdad_%281924%29.jpg",
    watchUrl: "https://archive.org/details/TheThiefofBagdad1924",
    embedUrl: "https://archive.org/embed/TheThiefofBagdad1924",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["silent", "fantasy", "arabian nights", "fairbanks", "epic"],
    featured: false,
    trending: true
  },
  // ── HISTORICAL ───────────────────────────────────────────
  {
    id: "birth-nation-1915",
    title: "Intolerance",
    year: 1916,
    director: "D.W. Griffith",
    cast: ["Lillian Gish", "Mae Marsh", "Fred Turner"],
    genre: ["Historical Films", "Drama", "Classic Cinema"],
    language: "en",
    country: "USA",
    runtime: 197,
    rating: 7.8,
    description: "Four parallel stories from different eras are interwoven to illustrate the theme of intolerance throughout history. Griffith's epic response to criticism of Birth of a Nation, featuring massive Babylonian sets.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Intolerance_%28film%29_poster.jpg/800px-Intolerance_%28film%29_poster.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Intolerance_%28film%29_poster.jpg",
    watchUrl: "https://archive.org/details/Intolerance_1916_silent",
    embedUrl: "https://archive.org/embed/Intolerance_1916_silent",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["griffith", "silent", "epic", "babylon", "parallel stories"],
    featured: false,
    trending: false
  },
  {
    id: "phantom-opera-1925",
    title: "The Phantom of the Opera",
    year: 1925,
    director: "Rupert Julian",
    cast: ["Lon Chaney", "Mary Philbin", "Norman Kerry"],
    genre: ["Horror", "Drama", "Classic Cinema", "Historical Films"],
    language: "en",
    country: "USA",
    runtime: 93,
    rating: 7.6,
    description: "A disfigured musical genius haunts the Paris Opera House and terrorizes the opera's management to make the woman he loves a star. Lon Chaney's iconic performance remains deeply unsettling.",
    poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/PhantomOfTheOpera1925Poster.jpg/800px-PhantomOfTheOpera1925Poster.jpg",
    backdrop: "https://upload.wikimedia.org/wikipedia/commons/0/06/PhantomOfTheOpera1925Poster.jpg",
    watchUrl: "https://archive.org/details/ThePhantomOfTheOpera1925",
    embedUrl: "https://archive.org/embed/ThePhantomOfTheOpera1925",
    license: "Public Domain",
    source: "Internet Archive",
    tags: ["lon chaney", "phantom", "opera", "horror", "gothic", "iconic"],
    featured: false,
    trending: false
  }
];

// Genre list
const GENRES = [
  "Classic Cinema",
  "Public Domain Films",
  "Independent Movies",
  "Documentaries",
  "Animation",
  "Science Fiction",
  "Adventure",
  "Drama",
  "Comedy",
  "Historical Films",
  "Horror",
  "Fantasy"
];

// Language map
const LANGUAGES = {
  en: "English",
  de: "German",
  fr: "French",
  ru: "Russian",
  es: "Spanish",
  ar: "Arabic",
  it: "Italian",
  ja: "Japanese"
};

// i18n strings
const I18N = {
  en: {
    appName: "Laye Movies",
    tagline: "Discover Cinema's Greatest Treasures",
    search: "Search movies, directors, genres...",
    trending: "Trending Now",
    featured: "Featured Films",
    classics: "Classic Cinema",
    hiddenGems: "Hidden Gems",
    newArrivals: "Recently Added",
    watchNow: "Watch Now",
    addFavorite: "Add to Favorites",
    watchLater: "Watch Later",
    favorites: "My Favorites",
    history: "Watch History",
    categories: "Categories",
    about: "About",
    director: "Director",
    cast: "Cast",
    genre: "Genre",
    runtime: "Runtime",
    year: "Year",
    country: "Country",
    language: "Language",
    rating: "Rating",
    license: "License",
    source: "Source",
    similarMovies: "Similar Movies",
    noResults: "No movies found",
    loading: "Loading...",
    minutes: "min",
    home: "Home",
    discover: "Discover",
    reels: "Reels",
    legal: "Legal & Free",
    publicDomain: "Public Domain",
    swipeHint: "Swipe up for next film"
  },
  ar: {
    appName: "لاي أفلام",
    tagline: "اكتشف كنوز السينما العظيمة",
    search: "ابحث عن أفلام ومخرجين وأنواع...",
    trending: "الرائج الآن",
    featured: "أفلام مميزة",
    classics: "السينما الكلاسيكية",
    hiddenGems: "جواهر مخفية",
    newArrivals: "أضيف مؤخراً",
    watchNow: "شاهد الآن",
    addFavorite: "أضف إلى المفضلة",
    watchLater: "شاهد لاحقاً",
    favorites: "مفضلاتي",
    history: "سجل المشاهدة",
    categories: "الفئات",
    about: "حول",
    director: "المخرج",
    cast: "الممثلون",
    genre: "النوع",
    runtime: "المدة",
    year: "السنة",
    country: "البلد",
    language: "اللغة",
    rating: "التقييم",
    license: "الرخصة",
    source: "المصدر",
    similarMovies: "أفلام مشابهة",
    noResults: "لم يتم العثور على أفلام",
    loading: "جارٍ التحميل...",
    minutes: "دقيقة",
    home: "الرئيسية",
    discover: "اكتشف",
    reels: "ريلز",
    legal: "قانوني ومجاني",
    publicDomain: "ملك عام",
    swipeHint: "اسحب للأعلى للفيلم التالي"
  },
  fr: {
    appName: "Laye Films",
    tagline: "Découvrez les Grands Trésors du Cinéma",
    search: "Rechercher films, réalisateurs, genres...",
    trending: "Tendances",
    featured: "Films en vedette",
    classics: "Cinéma Classique",
    hiddenGems: "Pépites cachées",
    newArrivals: "Récemment ajoutés",
    watchNow: "Regarder",
    addFavorite: "Ajouter aux favoris",
    watchLater: "À regarder plus tard",
    favorites: "Mes favoris",
    history: "Historique",
    categories: "Catégories",
    about: "À propos",
    director: "Réalisateur",
    cast: "Distribution",
    genre: "Genre",
    runtime: "Durée",
    year: "Année",
    country: "Pays",
    language: "Langue",
    rating: "Note",
    license: "Licence",
    source: "Source",
    similarMovies: "Films similaires",
    noResults: "Aucun film trouvé",
    loading: "Chargement...",
    minutes: "min",
    home: "Accueil",
    discover: "Découvrir",
    reels: "Reels",
    legal: "Légal et gratuit",
    publicDomain: "Domaine public",
    swipeHint: "Glissez vers le haut pour le prochain film"
  },
  es: {
    appName: "Laye Películas",
    tagline: "Descubre los Grandes Tesoros del Cine",
    search: "Buscar películas, directores, géneros...",
    trending: "Tendencias",
    featured: "Películas destacadas",
    classics: "Cine Clásico",
    hiddenGems: "Joyas ocultas",
    newArrivals: "Añadidos recientemente",
    watchNow: "Ver ahora",
    addFavorite: "Añadir a favoritos",
    watchLater: "Ver más tarde",
    favorites: "Mis favoritos",
    history: "Historial",
    categories: "Categorías",
    about: "Acerca de",
    director: "Director",
    cast: "Reparto",
    genre: "Género",
    runtime: "Duración",
    year: "Año",
    country: "País",
    language: "Idioma",
    rating: "Puntuación",
    license: "Licencia",
    source: "Fuente",
    similarMovies: "Películas similares",
    noResults: "No se encontraron películas",
    loading: "Cargando...",
    minutes: "min",
    home: "Inicio",
    discover: "Descubrir",
    reels: "Reels",
    legal: "Legal y gratis",
    publicDomain: "Dominio público",
    swipeHint: "Desliza hacia arriba para el siguiente film"
  }
};

// Export
window.MOVIES = MOVIES;
window.GENRES = GENRES;
window.LANGUAGES = LANGUAGES;
window.I18N = I18N;
